login:
    path:   /login
    defaults: { _controller: AcmeSecurityBundle:Security:login }
login_check:
    path:   /login_check
logout:
    path:   /logout
admin:
    path:  /admin
    defaults: { _controller: AcmeDemoBundle:Welcome:index }
